[font]
size = 10
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

[window]
opacity = 0.6

[env]
EDITOR = "/bin/nvim"
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
